// <auto-generated />
using System;
using HeTHongDanhGiaThuoc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeTHongDanhGiaThuoc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622092007_FixDecimalColumnTypes2")]
    partial class FixDecimalColumnTypes2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNen", b =>
                {
                    b.Property<int>("MaBenhNen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenBenhNen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaBenhNen");

                    b.ToTable("BenhNen", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNhanBenhNen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNen")
                        .HasColumnType("int");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayChanDoan")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaBenhNen");

                    b.HasIndex("MaBenhNhan", "MaBenhNen")
                        .IsUnique();

                    b.ToTable("BenhNhanBenhNen", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChiTietDanhGia", b =>
                {
                    b.Property<int>("MaChiTietDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDanhGia"));

                    b.Property<string>("CanhBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoPhuHopKhong")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DiemPhuHop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KhuyenNghi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuDungChiDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LieuMoiLanMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LyDoKhongPhuHop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<int?>("SoLanMoiNgay")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayDieuTri")
                        .HasColumnType("int");

                    b.Property<decimal?>("TongLieuNgayMg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTietDanhGia");

                    b.HasIndex("MaDanhGia");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDanhGia", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChongChiDinh", b =>
                {
                    b.Property<int>("MaChongChiDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChongChiDinh"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNen")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("MucDoNguyHiem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChongChiDinh");

                    b.HasIndex("MaBenhNen");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChongChiDinh", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("CanhBaoYTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuPhienDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetLuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhuyenNghiSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TyLePhuHop")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaNguoiDanhGia");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DiUngThuoc", b =>
                {
                    b.Property<int>("MaDiUng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiUng"));

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaHoatChat")
                        .HasColumnType("int");

                    b.Property<string>("MucDoDiUng")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDiUng");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaHoatChat");

                    b.ToTable("DiUngThuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("BenhHienTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("CanNang")
                        .HasColumnType("real");

                    b.Property<float?>("ChieuCao")
                        .HasColumnType("real");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaDinhDanhBenhNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaDinhDanhBenhNhan")
                        .IsUnique();

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("HoSoBenhNhan", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoatChat", b =>
                {
                    b.Property<int>("MaHoatChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoatChat"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaHoatChat");

                    b.HasIndex("TenHoatChat")
                        .IsUnique();

                    b.ToTable("HoatChat", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<decimal?>("CanNangToiDa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CanNangToiThieu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DangBaoChe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HuongDanSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LieuDungChuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LieuKhuyenNghiMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LieuToiDaMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LieuToiThieuMg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TanSuatToiDaMoiNgay")
                        .HasColumnType("int");

                    b.Property<string>("TenBietDuoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TinhTrangThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TuoiToiDa")
                        .HasColumnType("int");

                    b.Property<int?>("TuoiToiThieu")
                        .HasColumnType("int");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocDangSuDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LieuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaThuoc");

                    b.HasIndex("MaBenhNhan", "MaThuoc")
                        .IsUnique();

                    b.ToTable("ThuocDangSuDung", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocHoatChat", b =>
                {
                    b.Property<int>("MaThuocHoatChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuocHoatChat"));

                    b.Property<string>("HamLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoatChat")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.HasKey("MaThuocHoatChat");

                    b.HasIndex("MaHoatChat");

                    b.HasIndex("MaThuoc", "MaHoatChat")
                        .IsUnique();

                    b.ToTable("ThuocHoatChat", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.TuongTacThuoc", b =>
                {
                    b.Property<int>("MaTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuongTac"));

                    b.Property<int>("MaThuocA")
                        .HasColumnType("int");

                    b.Property<int>("MaThuocB")
                        .HasColumnType("int");

                    b.Property<string>("MoTaTuongTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoNghiemTrong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTuongTac");

                    b.HasIndex("MaThuocA");

                    b.HasIndex("MaThuocB");

                    b.ToTable("TuongTacThuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNhanBenhNen", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.BenhNen", "BenhNen")
                        .WithMany("BenhNhanBenhNens")
                        .HasForeignKey("MaBenhNen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("BenhNhanBenhNens")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNen");

                    b.Navigation("HoSoBenhNhan");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChiTietDanhGia", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.DanhGia", "DanhGia")
                        .WithMany("ChiTietDanhGias")
                        .HasForeignKey("MaDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDanhGias")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChongChiDinh", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.BenhNen", "BenhNen")
                        .WithMany("ChongChiDinhs")
                        .HasForeignKey("MaBenhNen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChongChiDinhs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNen");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.NguoiDung", "NguoiDanhGia")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDanhGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoBenhNhan");

                    b.Navigation("NguoiDanhGia");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DiUngThuoc", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("DiUngThuocs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoatChat", "HoatChat")
                        .WithMany("DiUngThuocs")
                        .HasForeignKey("MaHoatChat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoBenhNhan");

                    b.Navigation("HoatChat");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.NguoiDung", "NguoiTao")
                        .WithMany("HoSoBenhNhans")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocDangSuDung", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("ThuocDangSuDungs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoBenhNhan");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocHoatChat", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoatChat", "HoatChat")
                        .WithMany("ThuocHoatChats")
                        .HasForeignKey("MaHoatChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ThuocHoatChats")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoatChat");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.TuongTacThuoc", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "ThuocA")
                        .WithMany("TuongTacA")
                        .HasForeignKey("MaThuocA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "ThuocB")
                        .WithMany("TuongTacB")
                        .HasForeignKey("MaThuocB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThuocA");

                    b.Navigation("ThuocB");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNen", b =>
                {
                    b.Navigation("BenhNhanBenhNens");

                    b.Navigation("ChongChiDinhs");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.Navigation("ChiTietDanhGias");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.Navigation("BenhNhanBenhNens");

                    b.Navigation("DanhGias");

                    b.Navigation("DiUngThuocs");

                    b.Navigation("ThuocDangSuDungs");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoatChat", b =>
                {
                    b.Navigation("DiUngThuocs");

                    b.Navigation("ThuocHoatChats");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoSoBenhNhans");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDanhGias");

                    b.Navigation("ChongChiDinhs");

                    b.Navigation("ThuocHoatChats");

                    b.Navigation("TuongTacA");

                    b.Navigation("TuongTacB");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
