// <auto-generated />
using System;
using HeTHongDanhGiaThuoc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeTHongDanhGiaThuoc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260608055919_RecreateDB")]
    partial class RecreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNen", b =>
                {
                    b.Property<int>("MaBenhNen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNen"));

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayChanDoan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBenhNen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaBenhNen");

                    b.HasIndex("MaBenhNhan");

                    b.ToTable("BenhNen", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChiTietDanhGia", b =>
                {
                    b.Property<int>("MaChiTietDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDanhGia"));

                    b.Property<bool>("CoPhuHopKhong")
                        .HasColumnType("bit");

                    b.Property<string>("LieuDungChiDinh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LyDoKhongPhuHop")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDanhGia");

                    b.HasIndex("MaDanhGia");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietDanhGia", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChongChiDinh", b =>
                {
                    b.Property<int>("MaChongChiDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChongChiDinh"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("TenBenhChongChiDinh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaChongChiDinh");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChongChiDinh", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("CanhBaoYTe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuPhienDanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuyenNghiSuDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDanhGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TyLePhuHop")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaNguoiDanhGia");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DiUngThuoc", b =>
                {
                    b.Property<int>("MaDiUng")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiUng"));

                    b.Property<int?>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoatChat")
                        .HasColumnType("int");

                    b.Property<string>("MucDoDiUng")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDiUng");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaHoatChat");

                    b.ToTable("DiUngThuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaDinhDanhBenhNhan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTiepNhan")
                        .HasColumnType("datetime2");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaDinhDanhBenhNhan")
                        .IsUnique();

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("HoSoBenhNhan", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoatChat", b =>
                {
                    b.Property<int>("MaHoatChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoatChat"));

                    b.Property<string>("TenHoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaHoatChat");

                    b.HasIndex("TenHoatChat")
                        .IsUnique();

                    b.ToTable("HoatChat", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhauMaHoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            Email = "admin@hethong.com",
                            HoTen = "Quản trị viên",
                            MaVaiTro = 1,
                            MatKhauMaHoa = "$2a$11$LwHiYJeSfXcTwon7BtHoPuo2mmuMNv3Mt4ku1gl075l63vWBk3mWm",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            TrangThaiHoatDong = true
                        });
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<string>("DangBaoChe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LieuDungChuan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBietDuoc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TinhTrangThuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocHoatChat", b =>
                {
                    b.Property<int>("MaThuocHoatChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuocHoatChat"));

                    b.Property<string>("HamLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaHoatChat")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.HasKey("MaThuocHoatChat");

                    b.HasIndex("MaHoatChat");

                    b.HasIndex("MaThuoc");

                    b.ToTable("Thuoc_HoatChat", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.TuongTacThuoc", b =>
                {
                    b.Property<int>("MaTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuongTac"));

                    b.Property<int>("MaThuoc_A")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc_B")
                        .HasColumnType("int");

                    b.Property<string>("MoTaTuongTac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MucDoNghiemTrong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTuongTac");

                    b.HasIndex("MaThuoc_A");

                    b.HasIndex("MaThuoc_B");

                    b.ToTable("TuongTacThuoc", (string)null);
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "Bác sĩ"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "Dược sĩ"
                        },
                        new
                        {
                            MaVaiTro = 4,
                            TenVaiTro = "Y tá"
                        });
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.BenhNen", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("BenhNens")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("HoSoBenhNhan");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChiTietDanhGia", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.DanhGia", "DanhGia")
                        .WithMany("ChiTietDanhGias")
                        .HasForeignKey("MaDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietDanhGias")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ChongChiDinh", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ChongChiDinhs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeTHongDanhGiaThuoc.Models.NguoiDung", "NguoiDanhGia")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDanhGia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HoSoBenhNhan");

                    b.Navigation("NguoiDanhGia");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DiUngThuoc", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", "HoSoBenhNhan")
                        .WithMany("DiUngThuocs")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoatChat", "HoatChat")
                        .WithMany("DiUngThuocs")
                        .HasForeignKey("MaHoatChat")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HoSoBenhNhan");

                    b.Navigation("HoatChat");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.NguoiDung", "NguoiTao")
                        .WithMany("HoSoBenhNhans")
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.ThuocHoatChat", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.HoatChat", "HoatChat")
                        .WithMany("ThuocHoatChats")
                        .HasForeignKey("MaHoatChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "Thuoc")
                        .WithMany("ThuocHoatChats")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoatChat");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.TuongTacThuoc", b =>
                {
                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "ThuocA")
                        .WithMany("TuongTacA")
                        .HasForeignKey("MaThuoc_A")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeTHongDanhGiaThuoc.Models.Thuoc", "ThuocB")
                        .WithMany("TuongTacB")
                        .HasForeignKey("MaThuoc_B")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ThuocA");

                    b.Navigation("ThuocB");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.DanhGia", b =>
                {
                    b.Navigation("ChiTietDanhGias");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoSoBenhNhan", b =>
                {
                    b.Navigation("BenhNens");

                    b.Navigation("DanhGias");

                    b.Navigation("DiUngThuocs");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.HoatChat", b =>
                {
                    b.Navigation("DiUngThuocs");

                    b.Navigation("ThuocHoatChats");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("HoSoBenhNhans");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietDanhGias");

                    b.Navigation("ChongChiDinhs");

                    b.Navigation("ThuocHoatChats");

                    b.Navigation("TuongTacA");

                    b.Navigation("TuongTacB");
                });

            modelBuilder.Entity("HeTHongDanhGiaThuoc.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
